# Site configurations.

title: Data Analytics docs
description: Documentations for data Analytics
url: "https://sjeganraj.github.io/"


# Enable or disable the site search
search_enabled: true

theme: jekyll-theme-slate